config/routes.rb
# Add your custom routes here.  If in config/routes.rb you would 
# add <tt>map.resources</tt>, here you would add just <tt>resources</tt>

resources :jobs

app/models/available_job.rb
class AvailableJob < Job
    validates_presence_of :skills, :company_name, :designation
end

app/models/job.rb
class Job < ActiveRecord::Base
  def user_profile
    return user.profile
  end
  belongs_to :user
  cattr_reader :per_page
  @@per_page = 5
end

app/models/required_job.rb
class RequiredJob < Job
  validates_presence_of :education, :skills
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :jobs, :dependent => :destroy
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  before_filter :find_job, :only => [:show, :destroy, :edit, :update]
  before_filter :current_user?, :only => [:new, :create, :destroy, :edit, :update]
  before_filter :job_user?, :only => [:destroy, :edit, :update]
  
  def index
   @jobs = (params[:type] and params[:type].match(/required/)) ? RequiredJob.paginate(:page => params[:page] ? params[:page] : 1, :order => 'updated_at DESC') : AvailableJob.paginate(:page => params[:page] ? params[:page] : 1, :order => 'updated_at DESC')
  end
  
  def new
    @job = (params[:type] and params[:type].match(/required/)) ? RequiredJob.new() : AvailableJob.new()
  end
  
  def create
    @job = params[:available_job] ? AvailableJob.new(params[:available_job].merge({:user_id => current_user.id})) : RequiredJob.new(params[:required_job].merge({:user_id => current_user.id}))
    @job.save ? (redirect_to job_path(@job, :type => @job.class.to_s.downcase)) : (render :action => 'new')
  end
  
  def edit
    render :template => 'jobs/new'
  end
  
  def update
    @job.update_attributes(params[:job]) ? (redirect_to job_path(@job, :type => @job.class.to_s.downcase)) : (render :action => 'edit')
  end
  
  def show
  end
  
  def destroy
    flash[:ok] = "Job has been deleted successfully" if @job.destroy
    redirect_to :back
  end
  
 private ###########################
 
  def find_job
    @job = Job.find(params[:id]) rescue nil
    unless @job
      flash[:error] = "Sorry, the page cannot be found."
      redirect_to jobs_path
    end
  end
  
  def current_user?
    unless current_user
      flash[:error] = "Sorry we cannot process your request"
      redirect_to jobs_path
    end
  end
  
  def job_user?
    unless @job.user == current_user
      flash[:error] = "Sorry we cannot process your request"
      redirect_to jobs_path
    end
  end
 
end

app/helpers/jobs_helper.rb
module JobsHelper


  def head
    head_string = ""
    if current_user
      head_string = "#{(params[:type] and params[:type].match(/required/)) ? link_to('Jobs Required', new_job_path(:type => 'required'), :class => 'button add') : link_to('Post Jobs', new_job_path, :class => 'button add')}<br />"
    end
    head_string += "<h2> #{(params[:type] and params[:type].match(/required/)) ? 'Required Jobs' : 'Available Jobs'}</h2>"
    head_string += "#{(params[:type] and params[:type].match(/required/)) ? 'If you are a developer and wants a job then post requirements here' : 'If you are a company and wants to hire developers then Post Jobs here'}"
    return head_string
  end
  
  def if_empty(jobs)
    if jobs.nil? || jobs.empty?
      return "Be the first one to post a #{(params[:type] and params[:type].match(/required/)) ? link_to('Jobs Required', new_job_path(:type => 'required'), :class => 'button add') : link_to('Available Jobs', new_job_path, :class => 'button add')}"
    end
  end
  
  
end

app/views/jobs/_sidebar.html.erb
<ul>
  <li><%= link_to "Available Jobs", jobs_path %></li>
  <li><%= link_to "Required Jobs", jobs_path(:type=>"required") %></li>
</ul>

app/views/jobs/index.html.erb
<%= head %>
<br />
<br />
<%= if_empty(@jobs) %>
<% unless @jobs.nil? || @jobs.empty? %>
  <% for job in @jobs %>
    <% if job.class.to_s == "AvailableJob" %>
			<div class="job_designation">
				<%= h job.designation %>
			</div>
			<div class="job_company">
				<%= h job.company_name %>
			</div>
			<div class="job_skills">
				<%= h job.skills %>
			</div>
			<div class="job_experience">
				<%= h job.experience %>
			</div>
			<div class="job_posted_by">
				posted by <%= link_to job.user_profile.full_name, profile_path(job.user_profile) %>
			</div>
		<% else %>
			<div class="job_candidate">
				<%= link_to job.user_profile.full_name, profile_path(job.user_profile) %>
			</div>
			<div class="education">
				<%= h job.education %>
			</div>
			<div class="job_skills">
				<%= h job.skills %>
			</div>
			<div class="job_experience">
				<%= h job.experience %>
			</div>
		<% end %>
    <% if job.user == current_user %>
      <div class="job_edit">
        <%= link_to "Edit", edit_job_path(job) %>
      </div>
      <div class="job_delete">
        <%= link_to "Delete", job_path(job), :method => :delete, :confirm => 'Are you sure' %>
      </div>
    <% end %>
    <hr />
  <% end %>
  <%= will_paginate @jobs %>
<% end %>
<% content_for :sidebar do %>
  <%= render :partial => 'sidebar' %>
<% end %>

app/views/jobs/new.html.erb
<%= head %>
<br />
<br />
<% form_for @job, :url => jobs_path do |f| %>
  <div class="fields">
  <%= error_messages_for :job %>
  <% if @job.class.to_s == "AvailableJob" %>
    <p><%= f.label :designation %>
    <%= f.text_field :designation %></p>
    <p><%= f.label :company_name %>
    <%= f.text_field :company_name %></p>
  <% else %>
    <p><%= f.label :education %>
    <%= f.text_field :education %></p>
  <% end %>
    <p><%= f.label :skills %>
    <%= f.text_area :skills %></p>
    <p><%= f.label :experience %>
    <%= f.text_field :experience %></p>
  <div class="actions"><%= f.submit "submit", :class => 'button mainaction' %></div><br />
  </div>
<% end %>
<% content_for :sidebar do %>
  <%= render :partial => 'sidebar' %>
<% end %>

app/views/jobs/show.html.erb
<%= head %>
<br />
<br />
<% if @job.class.to_s == "AvailableJob" %>
  <div class="job_designation">
    <%= h @job.designation %>
  </div>
  <div class="job_company">
    <%= h @job.company_name %>
  </div>
  <div class="job_skills">
    <%= h @job.skills %>
  </div>
  <div class="job_experience">
    <%= h @job.experience %>
  </div>
  <div class="job_posted_by">
    posted by <%= link_to @job.user_profile.full_name, profile_path(@job.user_profile) %>
  </div>
<% else %>
  <div class="job_candidate">
    <%= link_to @job.user_profile.full_name, profile_path(@job.user_profile) %>
  </div>
  <div class="education">
    <%= h @job.education %>
  </div>
  <div class="job_skills">
    <%= h @job.skills %>
  </div>
  <div class="job_experience">
    <%= h @job.experience %>
  </div>
<% end %>
<% if @job.user == current_user %>
  <div class="job_edit">
    <%= link_to "Edit", edit_job_path(@job) %>
  </div>
  <div class="job_delete">
    <%= link_to "Delete", job_path(@job), :method => :delete, :confirm => 'Are you sure' %>
  </div>
<% end %>
<% content_for :sidebar do %>
  <%= render :partial => 'sidebar' %>
<% end %>